/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: struct.proto */

#ifndef PROTOBUF_C_struct_2eproto__INCLUDED
#define PROTOBUF_C_struct_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Unit Unit;


/* --- enums --- */


/* --- messages --- */

struct  Unit
{
  ProtobufCMessage base;
  int32_t a;
  int64_t b;
  char *c;
};
#define UNIT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&unit__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string }


/* Unit methods */
void   unit__init
                     (Unit         *message);
size_t unit__get_packed_size
                     (const Unit   *message);
size_t unit__pack
                     (const Unit   *message,
                      uint8_t             *out);
size_t unit__pack_to_buffer
                     (const Unit   *message,
                      ProtobufCBuffer     *buffer);
Unit *
       unit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   unit__free_unpacked
                     (Unit *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Unit_Closure)
                 (const Unit *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor unit__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_struct_2eproto__INCLUDED */
